export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE: 422,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500,
} as const;

export const ROLE = {
  CUSTOMER: 'CUSTOMER',
  TECHNICIAN: 'TECHNICIAN',
  MANAGER: 'MANAGER',
  ADMIN: 'ADMIN',
} as const;

export const ASSIGNMENT_STATUS_TRANSITIONS: Record<string, string[]> = {
  PENDING: ['SCHEDULED', 'CANCELLED'],
  SCHEDULED: ['ACCEPTED', 'REJECTED', 'CANCELLED'],
  ACCEPTED: ['ARRIVED'],
  REJECTED: [],
  CANCELLED: [],
};

export const WORK_ORDER_STATUS_TRANSITIONS: Record<string, string[]> = {
  SCHEDULED: ['ARRIVED', 'CANCELLED'],
  ARRIVED: ['IN_PROGRESS', 'CANCELLED'],
  IN_PROGRESS: ['COMPLETED', 'CANCELLED'],
  COMPLETED: [],
  CANCELLED: [],
};

export const SERVICE_REQUEST_STATUS_TRANSITIONS: Record<string, string[]> = {
  PENDING: ['UNDER_REVIEW', 'CANCELLED'],
  UNDER_REVIEW: ['APPROVED', 'REJECTED', 'CANCELLED'],
  APPROVED: ['UNDER_REVIEW', 'ASSIGNED', 'CANCELLED'],
  ASSIGNED: ['SCHEDULED', 'CANCELLED'],
  SCHEDULED: ['COMPLETED', 'CANCELLED'],
  COMPLETED: ['INVOICED'],
  INVOICED: ['PAID'],
  PAID: ['CLOSED'],
  REJECTED: [],
  CANCELLED: [],
  CLOSED: [],
};

export const INVOICE_STATUS_TRANSITIONS: Record<string, string[]> = {
  DRAFT: ['PENDING', 'VOID'],
  PENDING: ['PAID', 'PARTIALLY_PAID', 'VOID'],
  PAID: [],
  PARTIALLY_PAID: ['PAID', 'VOID'],
  VOID: [],
};
